---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1575315/public_html/warteg-kece.junaediakbar.com
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp hero.svg $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
